// src/components/main/footer/footer.jsx
import React from 'react';
import { FormattedMessage } from 'react-intl';

const footer = () => {

  const year = new Date().getFullYear();

  return <footer id="footer">
    <div className="container">
      <div className="row">
        <div className="col-md-12">
          <p className="copy"><FormattedMessage id="FOOTER.MAIN" /> Pablo Ibanez - {year}</p>
        </div>
      </div>
    </div>
  </footer>;
}

export default footer;

// src/app/sections/footer/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss']
})
export class FooterComponent {

  public year: number;

  constructor() {
    this.year = new Date().getFullYear();
  }

}

<footer id="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <p class="copy">
          {{year}} Pablo Ibanez.
        </p>
      </div>
    </div>
  </div>
</footer>
